"""MathGraph: a lightweight kernel for verifiable mathematical claims."""

from mathgraph.certificates import Certificate, TerminalForm, VerificationStatus
from mathgraph.alchemy import (
    AlchemicalPhase,
    AlchemicalStatus,
    AlchemicalStep,
    AlchemicalTrace,
    make_alchemical_trace_id,
)
from mathgraph.agent_biography import (
    AgentBiography,
    AgentExperience,
    AgentExperienceOutcome,
    AgentProfile,
    AgentStatus,
    HTiltLiteScore,
    score_route_htilt_lite,
)
from mathgraph.projection import (
    ProjectionCandidate,
    ProjectionResult,
    ProjectionRuleKind,
    ProjectionStatus,
    ProjectionTrace,
    advisory_similarity_projection,
    exact_known_projection,
    make_projection_candidate_id,
    make_projection_result_id,
    make_projection_trace_id,
    projection_trace_to_agent_experiences,
    projection_trace_to_alchemical_trace,
    run_projection_engine,
    source_weakening_false_projection,
    target_strengthening_false_projection,
    transitivity_projection,
)
from mathgraph.proof_verification import (
    ProofArtifact,
    ProofArtifactKind,
    ProofVerificationResult,
    ProofVerificationStatus,
    ProofVerificationTrace,
    ProofVerifierKind,
    chain_audit_proof,
    import_verified_proof,
    make_cut_candidate,
    make_lean_skeleton,
    make_lemma_candidate,
    make_proof_artifact_id,
    make_proof_result_id,
    make_proof_trace_id,
    make_theorem_schema,
    proof_verification_trace_to_agent_experiences,
    proof_verification_trace_to_alchemical_trace,
    proof_verification_trace_to_projection_candidates,
    run_proof_verification_pipeline,
    run_proof_verifier,
)
from mathgraph.roadmap_alignment import (
    RoadmapAlignmentFinding,
    RoadmapAlignmentReport,
    check_roadmap_alignment,
)
from mathgraph.route_telemetry import (
    HTiltTelemetrySummary,
    RouteTelemetryEvent,
    RouteTelemetryKind,
    RouteTelemetryLedger,
    RouteTelemetryOutcome,
    build_route_telemetry_ledger,
    killing_table,
    make_route_telemetry_event_id,
    make_route_telemetry_ledger_id,
    route_outcome_table,
    summarize_h_tilt_telemetry,
    telemetry_events_from_episode,
    transition_table,
)
from mathgraph.root_constructors import (
    ConstructorAttempt,
    ConstructorPlan as RootAwareConstructorPlan,
    RootConstructorKind,
    RootConstructorStatus,
    RootConstructorTrace,
    RootSignal,
    compile_constructor_plans as compile_root_constructor_plans,
    load_constructor_plans_jsonl,
    load_root_signals_json,
    load_root_signals_jsonl,
    make_constructor_attempt_id,
    make_constructor_plan_id,
    make_root_constructor_trace_id,
    make_root_signal_id,
    root_constructor_trace_to_agent_experiences,
    root_constructor_trace_to_alchemical_trace,
    root_constructor_trace_to_projection_candidates,
    run_constructor_attempts,
    run_root_aware_constructors,
)
from mathgraph.verification_episode import (
    VerificationEpisodeInput,
    VerificationEpisodeRouteDecision,
    VerificationEpisodeStatus,
    VerificationEpisodeTrace,
    VerificationRouteKind,
    choose_episode_routes,
    combine_episode_alchemical_trace,
    make_verification_episode_id,
    run_verification_episode,
)
from mathgraph.claims import GeneralClaim
from mathgraph.certificate_assimilation import (
    CertificateAssimilationConfig,
    CertificateAssimilationResult,
    CertificateAssimilationSummary,
    run_certificate_assimilation,
)
from mathgraph.asset_discovery import (
    AssetDiscoveryConfig,
    AssetDiscoveryResult,
    discover_mathgraph_assets,
)
from mathgraph.asset_materialization import (
    AssetMaterializationConfig,
    AssetMaterializationResult,
    materialize_mathgraph_assets,
)
from mathgraph.artifact_warehouse import (
    import_closure_oracle_csv,
    import_table_registry_csv,
    import_v16_6_2_elevated_false_dir,
    import_v16_7_root_atlas_dir,
    register_aot_kernel,
    register_domain_kernel_in_store,
    register_etp_kernel,
)
from mathgraph.chewing_smoke import (
    ChewingSmokeConfig,
    ChewingSmokeResult,
    ChewingSmokeStageResult,
    run_chewing_smoke,
)
from mathgraph.countermodel_importer import (
    CountermodelImportConfig,
    CountermodelImportResult,
    CountermodelImportRunResult,
    import_finite_countermodel_results,
)
from mathgraph.corpus import CertificateCorpus
from mathgraph.client import (
    MathGraphAnswer,
    MathGraphAuditError,
    MathGraphClient,
    MathGraphClientConfig,
)
from mathgraph.equations import Equation, parse_equation
from mathgraph.episode_learning import (
    AssimilationLearningRecord,
    ConstructorYieldStats,
    EpisodeLearningConfig,
    EpisodeLearningResult,
    ResidualBasinStats,
    RouteYieldStats,
    learn_from_assimilation_episodes,
)
from mathgraph.derived_certificates import (
    DerivedCertificate,
    DerivedCertificateGenerator,
    DerivedCertificateStats,
)
from mathgraph.domain_kernels import (
    DomainKernel,
    HostVerifier,
    ImportedTheoryObject,
    ImportedTheoryRelation,
    SemanticEmbedding as DomainKernelSemanticEmbedding,
    SemanticEmbeddingKind,
    TheoryObjectKind as ImportedTheoryObjectKind,
    TheoryRelationKind,
    make_aot_domain_kernel,
    make_etp_domain_kernel,
)
from mathgraph.denotation import (
    DenotationRecord,
    DenotationStatus,
    can_promote_denotation,
    require_denotes,
)
from mathgraph.formal_worlds import (
    FormalWorld,
    FormalWorldKind,
    aot_formal_world_precedent,
    etp_magma_formal_world,
)
from mathgraph.language_fragments import (
    LanguageFragment,
    aot_l23_precedent_fragment,
    etp_magma_equations_fragment,
)
from mathgraph.paradox_guards import (
    GuardSeverity,
    ParadoxGuard,
    ParadoxGuardKind,
    ParadoxGuardResult,
    aot_complex_term_guard,
    semantic_embedding_artifact_guard,
    set_collapse_guard,
)
from mathgraph.predication import (
    PredicateKind,
    PredicationFact,
    PredicationMode,
    encodes,
    exemplifies,
)
from mathgraph.reason_containment import ContainmentMode, ReasonContainmentRecord
from mathgraph.semantic_embeddings import (
    ArtifactRisk,
    EmbeddingKind,
    ProofTransportStatus,
    SemanticEmbedding,
)
from mathgraph.theory_objectification import (
    AnalyticTruth,
    TheoryDenotation,
    TheoryObjectKind,
    TheoryObjectificationMap,
    TheoryReading,
)
from mathgraph.object_language import (
    FormulaRole,
    ObjectLanguageFormula,
    ObjectLanguageKind,
    ObjectLanguageTerm,
    normalize_object_language_text,
)
from mathgraph.theory_registry import (
    InferenceRule,
    ProofMethod,
    ProofMethodKind,
    TheoryDeclaration,
    TheoryDeclarationKind,
)
from mathgraph.aot_scanner import AOTScannedDeclaration, AOTScanResult, scan_aot_repository
from mathgraph.isabelle_exports import (
    HostObjectTheoremLink,
    IsabelleExportRecord,
    IsabelleExportStatus,
)
from mathgraph.logical_workbench import (
    LogicWorkbench,
    WorkbenchLayer,
    WorkbenchLifecycleStatus,
    logikey_style_workbench,
    mathgraph_default_workbench,
)
from mathgraph.local_service import (
    MathGraphHTTPServer,
    MathGraphRequestHandler,
    make_server,
)
from mathgraph.embedding_strategies import (
    AutomationBias,
    EmbeddingStrategy,
    EmbeddingStrategyProfile,
    SemanticsRepresentation,
    SyntaxRepresentation,
)
from mathgraph.faithfulness import (
    CompletenessStatus,
    FaithfulnessAssessment,
    FaithfulnessStatus,
    SoundnessStatus,
)
from mathgraph.logic_combinations import CombinationMethod, ConflictPolicy, LogicCombination
from mathgraph.verifier_backends import (
    BackendRole,
    VerifierBackendKind,
    VerifierBackendProfile,
    isabelle_nitpick_backend_placeholder,
    isabelle_nunchaku_backend_placeholder,
    isabelle_sledgehammer_backend_placeholder,
    lean_backend_placeholder,
    python_finite_table_checker_backend,
)
from mathgraph.backend_results import (
    ModelFinderResult,
    ModelFinderStatus,
    ProofFinderResult,
    ProofFinderStatus,
)
from mathgraph.benchmarking import (
    BenchmarkCase,
    BenchmarkExpectedStatus,
    BenchmarkObservedStatus,
    BenchmarkResult,
    BenchmarkRun,
    BenchmarkSuite,
    etp_matrix_benchmark_suite_metadata,
    logikey_methodology_benchmark_suite_metadata,
)
from mathgraph.correspondence import (
    CorrespondenceClaim,
    CorrespondenceDirection,
    CorrespondenceStatus,
)
from mathgraph.interpretation_choice import ChoicePointStatus, InterpretationChoicePoint
from mathgraph.workbench_presets import (
    build_logikey_style_workbench_bundle,
    build_mathgraph_etp_workbench_bundle,
)
from mathgraph.proof_motifs import (
    ProofMotif,
    ProofMotifKind,
    ProofRouteStatus,
    infer_proof_motif_kind,
    make_proof_motif_id,
)
from mathgraph.lemma_candidates import (
    CutIntroductionKind,
    LemmaCandidate,
    LemmaCandidateStatus,
    canonical_lemma_name,
    make_lemma_candidate_id,
)
from mathgraph.lean_artifacts import (
    LeanArtifact,
    LeanArtifactKind,
    LeanVerificationStatus,
    render_lean_skeleton,
)
from mathgraph.proof_atlas import ProofAtlas, build_proof_atlas_from_true_rows
from mathgraph.proof_importers import (
    discover_true_proof_artifacts,
    import_true_proof_artifacts_to_store,
    load_true_proof_rows,
    normalize_true_proof_row,
)
from mathgraph.metabolic_cycle import (
    MetabolicCycleConfig,
    MetabolicCycleResult,
    MetabolicCycleStageResult,
    run_metabolic_cycle,
)
from mathgraph.m0_certificate_factory import (
    M0EpisodeConfig,
    M0EpisodeMetrics,
    M0EpisodeResult,
    M0PairResult,
    run_m0_episode,
)
from mathgraph.m0_audit import AuditFinding, AuditReport, audit_m0_store
from mathgraph.terminal_contract import (
    TerminalContractResult,
    VerifierBoundary,
)
from mathgraph.metabolic_diagnostics import (
    MetabolicDiagnostics,
    compute_derived_amplification_factor,
    compute_residual_compression_gain,
    evaluate_better_shaped_unknown,
)
from mathgraph.synthetic_cycle_data import build_synthetic_metabolic_frontier
from mathgraph.types import (
    ExtensionalCollapsePolicy,
    HyperintensionalIdentityMode,
    MathGraphType,
    ObjectIdentityMode,
    TypeParseError,
    TypedObject,
    UniquenessStatus,
    canonical_encoded_object_id,
    normalize_type_expr,
    parse_type_expr,
    should_merge_objects,
)
from mathgraph.artifact_importers import (
    load_v1662_elevated_false_certificates,
    load_v167_obstructions,
    load_v167_reason_nodes,
    load_v167_root_nodes,
)
from mathgraph.hashing import (
    canonical_json,
    content_id,
    hash_certificate,
    hash_file,
    hash_trace,
    sha256_hex,
    sha256_json,
    sha256_text,
)
from mathgraph.flywheel import (
    FlywheelConfig,
    FlywheelResult,
    FlywheelStageResult,
    run_mathgraph_flywheel,
)
from mathgraph.frontier_builder import (
    FrontierBuilderConfig,
    FrontierBuilderResult,
    FrontierCandidate,
    KnownPairFilter,
    build_candidate_frontier,
)
from mathgraph.finite_countermodel_executor import (
    FiniteCountermodelConfig,
    FiniteCountermodelResult,
    FiniteCountermodelRunResult,
    run_finite_countermodel_tasks,
)
from mathgraph.htilt_scheduler import (
    HTiltScheduler,
    HTiltSchedulerStats,
    HTiltScoreBreakdown,
    ScheduledTask,
    SchedulerInputPair,
)
from mathgraph.kernel import Kernel
from mathgraph.kernel_oracle import KernelOracle, OracleAnswer
from mathgraph.lawbook import CertificateLawbook
from mathgraph.lawbook_store import LawbookStore, LawbookStoreStats
from mathgraph.ledger import JsonlLedger
from mathgraph.outcome_dataset import (
    CompoundingDiagnostics,
    OutcomeDatasetBuilder,
    OutcomeDatasetStats,
    PairOutcome,
    extract_pair_features as extract_outcome_pair_features,
)
from mathgraph.obstruction_atlas import ConstructorPressure, ObstructionNode
from mathgraph.pair_advisor import PairAdvice, advise_many, advise_pair, extract_pair_features
from mathgraph.reason_nodes import ReasonNode
from mathgraph.refutations import RefutationCertificate
from mathgraph.root_consolidation import consolidate_root_nodes
from mathgraph.root_nodes import (
    RootAlias,
    RootCertificateCoverage,
    RootNode,
    RootObstructionLink,
    RootReasonLink,
)
from mathgraph.root_discovery import (
    CompletionTelemetryRow,
    ConstructorFamilyCard,
    ObstructionCandidate,
    RootCandidate,
    RootDiscoveryScore,
    RootDiscoverySignals,
    attach_root_discovery_scores,
    build_constructor_family_cards,
    build_replay_queue,
    distill_obstruction_candidates,
    distill_root_candidates,
    score_root_candidate,
    score_root_candidates,
    summarize_root_discovery,
)
from mathgraph.persistent_filtration import (
    FiltrationEvidence,
    FiltrationSpec,
    PersistentFiltrationSummary,
    build_filtration_evidence,
    default_filtration_specs,
    summarize_persistence,
)
from mathgraph.root_shadow_collapse import (
    RootShadowCollapseResult,
    ShadowLink,
    choose_canonical_root,
    collapse_root_shadows,
    root_overlap_score,
)
from mathgraph.root_promotion import (
    RootPromotionPolicy,
    RootPromotionRecord,
    promote_roots,
    promotion_summary,
)
from mathgraph.root_compiler import (
    ConstructorPlan,
    choose_constructor_type,
    compile_constructor_plans,
)
from mathgraph.root_constructor_lab import (
    ConstructorFamilyResult,
    RootBasinPair,
    RootConstructorLabReport,
    RootHypothesis,
    RootValidationResult,
    default_root_hypotheses,
    detect_root_basin,
    run_root_constructor_lab,
    score_pair_for_root,
)
from mathgraph.continuation_traces import (
    ContinuationTrace,
    ContinuationTraceStore,
    make_trace_id,
)
from mathgraph.replay_engine import (
    ReplayReport,
    RouteReplaySignal,
    replay_continuation_traces,
)
from mathgraph.route_policy_v2 import (
    RoutePolicyV2Card,
    RoutePolicyV2Report,
    build_route_policy_v2_from_replay,
    build_route_policy_v2_from_trace_store,
    write_route_policy_v2,
)
from mathgraph.route_policy_scheduler_adapter import (
    RoutePriorityHint,
    match_priority_hint,
    route_policy_to_priority_hints,
)
from mathgraph.residual_atlas import (
    ResidualAtlasReport,
    ResidualCase,
    ResidualCluster,
    build_residual_atlas_from_rows,
    build_residual_atlas_from_traces,
    write_residual_atlas,
)
from mathgraph.frontier_v2 import (
    FrontierTaskV2,
    FrontierV2Report,
    build_frontier_v2_from_atlas,
    frontier_v2_to_task_queue_rows,
    write_frontier_v2,
)
from mathgraph.episode_runner_v2 import (
    EpisodeRunnerV2Config,
    EpisodeRunnerV2Report,
    EpisodeTaskResult,
    run_episode_v2,
)
from mathgraph.multi_episode_harness import (
    EpisodeSummaryRow,
    MultiEpisodeConfig,
    MultiEpisodeReport,
    run_multi_episode_harness,
)
from mathgraph.root_oracle import RootNodeOracle
from mathgraph.route_instructor import (
    RouteInstruction,
    build_all_route_instructions,
    build_route_instruction,
    route_instruction_report,
)
from mathgraph.route_learner import (
    RouteBasinKey,
    RouteLearner,
    RouteLearnerStats,
    RoutePolicyCard,
    RouteRecommendation,
    make_basin_key,
)
from mathgraph.task_planner import (
    CertificateTask,
    plan_certificate_task,
    plan_many_certificate_tasks,
)
from mathgraph.task_queue import (
    TaskQueueConfig,
    TaskQueueItem,
    TaskQueueResult,
    build_task_queue,
)
from mathgraph.task_runner import (
    TaskOutcome,
    TaskRunSummary,
    execute_certificate_task,
    execute_many_certificate_tasks,
    read_outcomes_json,
    read_outcomes_jsonl,
    residual_outcomes,
    summarize_task_outcomes,
    write_outcomes_json,
    write_outcomes_jsonl,
)
from mathgraph.terms import Term, parse_term
from mathgraph.trace import Trace
from mathgraph.trust import ProvenanceType, TrustLevel
from mathgraph.verify_api import MathGraphVerifier, VerifyConfig, VerifyRequest, VerifyResult

__all__ = [
    "AgentBiography",
    "AgentExperience",
    "AgentExperienceOutcome",
    "AgentProfile",
    "AgentStatus",
    "AlchemicalPhase",
    "AlchemicalStatus",
    "AlchemicalStep",
    "AlchemicalTrace",
    "Certificate",
    "CertificateAssimilationConfig",
    "CertificateAssimilationResult",
    "CertificateAssimilationSummary",
    "CertificateCorpus",
    "CertificateLawbook",
    "CertificateTask",
    "ConstructorPressure",
    "AssetDiscoveryConfig",
    "AssetDiscoveryResult",
    "AssetMaterializationConfig",
    "AssetMaterializationResult",
    "AssimilationLearningRecord",
    "ChewingSmokeConfig",
    "ChewingSmokeResult",
    "ChewingSmokeStageResult",
    "CompoundingDiagnostics",
    "CountermodelImportConfig",
    "CountermodelImportResult",
    "CountermodelImportRunResult",
    "DerivedCertificate",
    "DerivedCertificateGenerator",
    "DerivedCertificateStats",
    "DomainKernel",
    "Equation",
    "GeneralClaim",
    "EpisodeLearningConfig",
    "EpisodeLearningResult",
    "EpisodeRunnerV2Config",
    "EpisodeRunnerV2Report",
    "EpisodeTaskResult",
    "EpisodeSummaryRow",
    "FiniteCountermodelConfig",
    "FiniteCountermodelResult",
    "FiniteCountermodelRunResult",
    "FlywheelConfig",
    "FlywheelResult",
    "FlywheelStageResult",
    "FrontierBuilderConfig",
    "FrontierBuilderResult",
    "FrontierCandidate",
    "FrontierTaskV2",
    "FrontierV2Report",
    "HTiltLiteScore",
    "HTiltScheduler",
    "HTiltSchedulerStats",
    "HTiltScoreBreakdown",
    "HostVerifier",
    "ImportedTheoryObject",
    "ImportedTheoryRelation",
    "Kernel",
    "KernelOracle",
    "KnownPairFilter",
    "JsonlLedger",
    "LawbookStore",
    "LawbookStoreStats",
    "MathGraphVerifier",
    "OracleAnswer",
    "ObstructionNode",
    "OutcomeDatasetBuilder",
    "OutcomeDatasetStats",
    "PairAdvice",
    "PairOutcome",
    "ProvenanceType",
    "ProjectionCandidate",
    "ProjectionResult",
    "ProjectionRuleKind",
    "ProjectionStatus",
    "ProjectionTrace",
    "ReasonNode",
    "RefutationCertificate",
    "RoadmapAlignmentFinding",
    "RoadmapAlignmentReport",
    "RouteBasinKey",
    "RouteLearner",
    "RouteLearnerStats",
    "RouteYieldStats",
    "ConstructorYieldStats",
    "ResidualBasinStats",
    "RootAlias",
    "RootCertificateCoverage",
    "TaskOutcome",
    "TaskQueueConfig",
    "TaskQueueItem",
    "TaskQueueResult",
    "TaskRunSummary",
    "canonical_json",
    "RouteInstruction",
    "RootNode",
    "RootNodeOracle",
    "CompletionTelemetryRow",
    "ConstructorPlan",
    "ConstructorFamilyCard",
    "ConstructorFamilyResult",
    "ConstructorAttempt",
    "ContinuationTrace",
    "ContinuationTraceStore",
    "FiltrationEvidence",
    "FiltrationSpec",
    "ObstructionCandidate",
    "PersistentFiltrationSummary",
    "ReplayReport",
    "ResidualAtlasReport",
    "ResidualCase",
    "ResidualCluster",
    "RouteReplaySignal",
    "RoutePolicyV2Card",
    "RoutePolicyV2Report",
    "RoutePriorityHint",
    "RootBasinPair",
    "RootCandidate",
    "RootAwareConstructorPlan",
    "RootConstructorLabReport",
    "RootConstructorKind",
    "RootConstructorStatus",
    "RootConstructorTrace",
    "RootDiscoveryScore",
    "RootDiscoverySignals",
    "RootHypothesis",
    "RootPromotionPolicy",
    "RootPromotionRecord",
    "RootShadowCollapseResult",
    "RootValidationResult",
    "ShadowLink",
    "attach_root_discovery_scores",
    "build_filtration_evidence",
    "build_constructor_family_cards",
    "build_replay_queue",
    "build_frontier_v2_from_atlas",
    "build_route_policy_v2_from_replay",
    "build_route_policy_v2_from_trace_store",
    "build_residual_atlas_from_rows",
    "build_residual_atlas_from_traces",
    "choose_canonical_root",
    "choose_constructor_type",
    "choose_episode_routes",
    "collapse_root_shadows",
    "compile_constructor_plans",
    "compile_root_constructor_plans",
    "combine_episode_alchemical_trace",
    "default_filtration_specs",
    "default_root_hypotheses",
    "detect_root_basin",
    "distill_obstruction_candidates",
    "distill_root_candidates",
    "promote_roots",
    "promotion_summary",
    "root_overlap_score",
    "run_root_constructor_lab",
    "make_alchemical_trace_id",
    "make_trace_id",
    "match_priority_hint",
    "replay_continuation_traces",
    "route_policy_to_priority_hints",
    "score_root_candidate",
    "score_root_candidates",
    "score_pair_for_root",
    "score_route_htilt_lite",
    "summarize_persistence",
    "summarize_root_discovery",
    "write_route_policy_v2",
    "write_residual_atlas",
    "frontier_v2_to_task_queue_rows",
    "write_frontier_v2",
    "RootObstructionLink",
    "RootReasonLink",
    "RootSignal",
    "RoutePolicyCard",
    "RouteRecommendation",
    "ScheduledTask",
    "SchedulerInputPair",
    "SemanticEmbedding",
    "SemanticEmbeddingKind",
    "build_all_route_instructions",
    "build_route_instruction",
    "build_candidate_frontier",
    "build_task_queue",
    "check_roadmap_alignment",
    "advisory_similarity_projection",
    "advise_many",
    "advise_pair",
    "content_id",
    "consolidate_root_nodes",
    "discover_mathgraph_assets",
    "extract_pair_features",
    "extract_outcome_pair_features",
    "execute_certificate_task",
    "execute_many_certificate_tasks",
    "exact_known_projection",
    "hash_certificate",
    "hash_file",
    "hash_trace",
    "import_finite_countermodel_results",
    "import_closure_oracle_csv",
    "import_table_registry_csv",
    "import_v16_6_2_elevated_false_dir",
    "import_v16_7_root_atlas_dir",
    "learn_from_assimilation_episodes",
    "load_v1662_elevated_false_certificates",
    "load_v167_obstructions",
    "load_v167_reason_nodes",
    "load_v167_root_nodes",
    "load_constructor_plans_jsonl",
    "load_root_signals_json",
    "load_root_signals_jsonl",
    "make_basin_key",
    "make_aot_domain_kernel",
    "make_constructor_attempt_id",
    "make_constructor_plan_id",
    "make_projection_candidate_id",
    "make_projection_result_id",
    "make_projection_trace_id",
    "make_root_constructor_trace_id",
    "make_root_signal_id",
    "materialize_mathgraph_assets",
    "sha256_hex",
    "sha256_json",
    "sha256_text",
    "Term",
    "TerminalForm",
    "parse_equation",
    "parse_term",
    "plan_certificate_task",
    "plan_many_certificate_tasks",
    "read_outcomes_json",
    "read_outcomes_jsonl",
    "residual_outcomes",
    "register_aot_kernel",
    "register_domain_kernel_in_store",
    "register_etp_kernel",
    "projection_trace_to_agent_experiences",
    "projection_trace_to_alchemical_trace",
    "root_constructor_trace_to_agent_experiences",
    "root_constructor_trace_to_alchemical_trace",
    "root_constructor_trace_to_projection_candidates",
    "route_instruction_report",
    "run_mathgraph_flywheel",
    "run_chewing_smoke",
    "run_certificate_assimilation",
    "run_finite_countermodel_tasks",
    "run_projection_engine",
    "run_constructor_attempts",
    "run_root_aware_constructors",
    "summarize_task_outcomes",
    "source_weakening_false_projection",
    "target_strengthening_false_projection",
    "transitivity_projection",
    "Trace",
    "TrustLevel",
    "TheoryObjectKind",
    "TheoryRelationKind",
    "VerificationStatus",
    "VerifyConfig",
    "VerifyRequest",
    "VerifyResult",
    "write_outcomes_json",
    "write_outcomes_jsonl",
    "ArtifactRisk",
    "AnalyticTruth",
    "ContainmentMode",
    "DenotationRecord",
    "DenotationStatus",
    "DomainKernelSemanticEmbedding",
    "EmbeddingKind",
    "ExtensionalCollapsePolicy",
    "FormalWorld",
    "FormalWorldKind",
    "GuardSeverity",
    "HyperintensionalIdentityMode",
    "ImportedTheoryObjectKind",
    "LanguageFragment",
    "MathGraphType",
    "ObjectIdentityMode",
    "ParadoxGuard",
    "ParadoxGuardKind",
    "ParadoxGuardResult",
    "PredicateKind",
    "PredicationFact",
    "PredicationMode",
    "ProofTransportStatus",
    "ReasonContainmentRecord",
    "TheoryDenotation",
    "TheoryObjectificationMap",
    "TheoryReading",
    "TypeParseError",
    "TypedObject",
    "UniquenessStatus",
    "aot_complex_term_guard",
    "aot_formal_world_precedent",
    "aot_l23_precedent_fragment",
    "canonical_encoded_object_id",
    "can_promote_denotation",
    "encodes",
    "etp_magma_equations_fragment",
    "etp_magma_formal_world",
    "exemplifies",
    "make_etp_domain_kernel",
    "normalize_type_expr",
    "parse_type_expr",
    "require_denotes",
    "semantic_embedding_artifact_guard",
    "set_collapse_guard",
    "should_merge_objects",
    "AOTScanResult",
    "AOTScannedDeclaration",
    "FormulaRole",
    "HostObjectTheoremLink",
    "InferenceRule",
    "IsabelleExportRecord",
    "IsabelleExportStatus",
    "ObjectLanguageFormula",
    "ObjectLanguageKind",
    "ObjectLanguageTerm",
    "ProofMethod",
    "ProofMethodKind",
    "ProofArtifact",
    "ProofArtifactKind",
    "ProofVerificationResult",
    "ProofVerificationStatus",
    "ProofVerificationTrace",
    "ProofVerifierKind",
    "TheoryDeclaration",
    "TheoryDeclarationKind",
    "normalize_object_language_text",
    "scan_aot_repository",
    "AutomationBias",
    "BackendRole",
    "BenchmarkCase",
    "BenchmarkExpectedStatus",
    "BenchmarkObservedStatus",
    "BenchmarkResult",
    "BenchmarkRun",
    "BenchmarkSuite",
    "ChoicePointStatus",
    "CombinationMethod",
    "CompletenessStatus",
    "ConflictPolicy",
    "CorrespondenceClaim",
    "CorrespondenceDirection",
    "CorrespondenceStatus",
    "EmbeddingStrategy",
    "EmbeddingStrategyProfile",
    "FaithfulnessAssessment",
    "FaithfulnessStatus",
    "InterpretationChoicePoint",
    "LogicCombination",
    "LogicWorkbench",
    "ModelFinderResult",
    "ModelFinderStatus",
    "ProofFinderResult",
    "ProofFinderStatus",
    "SemanticsRepresentation",
    "SoundnessStatus",
    "SyntaxRepresentation",
    "VerifierBackendKind",
    "VerifierBackendProfile",
    "VerificationEpisodeInput",
    "VerificationEpisodeRouteDecision",
    "VerificationEpisodeStatus",
    "VerificationEpisodeTrace",
    "VerificationRouteKind",
    "HTiltTelemetrySummary",
    "RouteTelemetryEvent",
    "RouteTelemetryKind",
    "RouteTelemetryLedger",
    "RouteTelemetryOutcome",
    "WorkbenchLayer",
    "WorkbenchLifecycleStatus",
    "build_logikey_style_workbench_bundle",
    "build_mathgraph_etp_workbench_bundle",
    "etp_matrix_benchmark_suite_metadata",
    "isabelle_nitpick_backend_placeholder",
    "isabelle_nunchaku_backend_placeholder",
    "isabelle_sledgehammer_backend_placeholder",
    "lean_backend_placeholder",
    "logikey_methodology_benchmark_suite_metadata",
    "logikey_style_workbench",
    "mathgraph_default_workbench",
    "python_finite_table_checker_backend",
    "ProofMotif",
    "ProofMotifKind",
    "ProofRouteStatus",
    "make_proof_motif_id",
    "infer_proof_motif_kind",
    "LemmaCandidate",
    "LemmaCandidateStatus",
    "CutIntroductionKind",
    "chain_audit_proof",
    "import_verified_proof",
    "make_cut_candidate",
    "make_lean_skeleton",
    "make_lemma_candidate",
    "make_lemma_candidate_id",
    "make_proof_artifact_id",
    "make_proof_result_id",
    "make_proof_trace_id",
    "make_theorem_schema",
    "make_route_telemetry_event_id",
    "make_route_telemetry_ledger_id",
    "make_verification_episode_id",
    "canonical_lemma_name",
    "LeanArtifact",
    "LeanArtifactKind",
    "LeanVerificationStatus",
    "render_lean_skeleton",
    "ProofAtlas",
    "build_proof_atlas_from_true_rows",
    "discover_true_proof_artifacts",
    "load_true_proof_rows",
    "normalize_true_proof_row",
    "import_true_proof_artifacts_to_store",
    "MetabolicCycleConfig",
    "MetabolicCycleResult",
    "MetabolicCycleStageResult",
    "MetabolicDiagnostics",
    "M0EpisodeConfig",
    "M0EpisodeMetrics",
    "M0EpisodeResult",
    "M0PairResult",
    "MultiEpisodeConfig",
    "MultiEpisodeReport",
    "MathGraphAnswer",
    "MathGraphAuditError",
    "MathGraphClient",
    "MathGraphClientConfig",
    "MathGraphHTTPServer",
    "MathGraphRequestHandler",
    "AuditFinding",
    "AuditReport",
    "TerminalContractResult",
    "VerifierBoundary",
    "build_synthetic_metabolic_frontier",
    "compute_derived_amplification_factor",
    "compute_residual_compression_gain",
    "evaluate_better_shaped_unknown",
    "run_m0_episode",
    "run_episode_v2",
    "run_multi_episode_harness",
    "proof_verification_trace_to_agent_experiences",
    "proof_verification_trace_to_alchemical_trace",
    "proof_verification_trace_to_projection_candidates",
    "run_proof_verification_pipeline",
    "run_proof_verifier",
    "build_route_telemetry_ledger",
    "killing_table",
    "route_outcome_table",
    "summarize_h_tilt_telemetry",
    "telemetry_events_from_episode",
    "transition_table",
    "run_verification_episode",
    "audit_m0_store",
    "make_server",
    "run_metabolic_cycle",
]
