"""MathGraph: a lightweight kernel for verifiable mathematical claims."""

from mathgraph.certificates import Certificate, TerminalForm, VerificationStatus
from mathgraph.claims import GeneralClaim
from mathgraph.certificate_assimilation import (
    CertificateAssimilationConfig,
    CertificateAssimilationResult,
    CertificateAssimilationSummary,
    run_certificate_assimilation,
)
from mathgraph.asset_discovery import (
    AssetDiscoveryConfig,
    AssetDiscoveryResult,
    discover_mathgraph_assets,
)
from mathgraph.asset_materialization import (
    AssetMaterializationConfig,
    AssetMaterializationResult,
    materialize_mathgraph_assets,
)
from mathgraph.artifact_warehouse import (
    import_closure_oracle_csv,
    import_table_registry_csv,
    import_v16_6_2_elevated_false_dir,
    import_v16_7_root_atlas_dir,
    register_aot_kernel,
    register_domain_kernel_in_store,
    register_etp_kernel,
)
from mathgraph.chewing_smoke import (
    ChewingSmokeConfig,
    ChewingSmokeResult,
    ChewingSmokeStageResult,
    run_chewing_smoke,
)
from mathgraph.countermodel_importer import (
    CountermodelImportConfig,
    CountermodelImportResult,
    CountermodelImportRunResult,
    import_finite_countermodel_results,
)
from mathgraph.corpus import CertificateCorpus
from mathgraph.client import (
    MathGraphAnswer,
    MathGraphAuditError,
    MathGraphClient,
    MathGraphClientConfig,
)
from mathgraph.equations import Equation, parse_equation
from mathgraph.episode_learning import (
    AssimilationLearningRecord,
    ConstructorYieldStats,
    EpisodeLearningConfig,
    EpisodeLearningResult,
    ResidualBasinStats,
    RouteYieldStats,
    learn_from_assimilation_episodes,
)
from mathgraph.derived_certificates import (
    DerivedCertificate,
    DerivedCertificateGenerator,
    DerivedCertificateStats,
)
from mathgraph.domain_kernels import (
    DomainKernel,
    HostVerifier,
    ImportedTheoryObject,
    ImportedTheoryRelation,
    SemanticEmbedding as DomainKernelSemanticEmbedding,
    SemanticEmbeddingKind,
    TheoryObjectKind as ImportedTheoryObjectKind,
    TheoryRelationKind,
    make_aot_domain_kernel,
    make_etp_domain_kernel,
)
from mathgraph.denotation import (
    DenotationRecord,
    DenotationStatus,
    can_promote_denotation,
    require_denotes,
)
from mathgraph.formal_worlds import (
    FormalWorld,
    FormalWorldKind,
    aot_formal_world_precedent,
    etp_magma_formal_world,
)
from mathgraph.language_fragments import (
    LanguageFragment,
    aot_l23_precedent_fragment,
    etp_magma_equations_fragment,
)
from mathgraph.paradox_guards import (
    GuardSeverity,
    ParadoxGuard,
    ParadoxGuardKind,
    ParadoxGuardResult,
    aot_complex_term_guard,
    semantic_embedding_artifact_guard,
    set_collapse_guard,
)
from mathgraph.predication import (
    PredicateKind,
    PredicationFact,
    PredicationMode,
    encodes,
    exemplifies,
)
from mathgraph.reason_containment import ContainmentMode, ReasonContainmentRecord
from mathgraph.semantic_embeddings import (
    ArtifactRisk,
    EmbeddingKind,
    ProofTransportStatus,
    SemanticEmbedding,
)
from mathgraph.theory_objectification import (
    AnalyticTruth,
    TheoryDenotation,
    TheoryObjectKind,
    TheoryObjectificationMap,
    TheoryReading,
)
from mathgraph.object_language import (
    FormulaRole,
    ObjectLanguageFormula,
    ObjectLanguageKind,
    ObjectLanguageTerm,
    normalize_object_language_text,
)
from mathgraph.theory_registry import (
    InferenceRule,
    ProofMethod,
    ProofMethodKind,
    TheoryDeclaration,
    TheoryDeclarationKind,
)
from mathgraph.aot_scanner import AOTScannedDeclaration, AOTScanResult, scan_aot_repository
from mathgraph.isabelle_exports import (
    HostObjectTheoremLink,
    IsabelleExportRecord,
    IsabelleExportStatus,
)
from mathgraph.logical_workbench import (
    LogicWorkbench,
    WorkbenchLayer,
    WorkbenchLifecycleStatus,
    logikey_style_workbench,
    mathgraph_default_workbench,
)
from mathgraph.local_service import (
    MathGraphHTTPServer,
    MathGraphRequestHandler,
    make_server,
)
from mathgraph.embedding_strategies import (
    AutomationBias,
    EmbeddingStrategy,
    EmbeddingStrategyProfile,
    SemanticsRepresentation,
    SyntaxRepresentation,
)
from mathgraph.faithfulness import (
    CompletenessStatus,
    FaithfulnessAssessment,
    FaithfulnessStatus,
    SoundnessStatus,
)
from mathgraph.logic_combinations import CombinationMethod, ConflictPolicy, LogicCombination
from mathgraph.verifier_backends import (
    BackendRole,
    VerifierBackendKind,
    VerifierBackendProfile,
    isabelle_nitpick_backend_placeholder,
    isabelle_nunchaku_backend_placeholder,
    isabelle_sledgehammer_backend_placeholder,
    lean_backend_placeholder,
    python_finite_table_checker_backend,
)
from mathgraph.backend_results import (
    ModelFinderResult,
    ModelFinderStatus,
    ProofFinderResult,
    ProofFinderStatus,
)
from mathgraph.benchmarking import (
    BenchmarkCase,
    BenchmarkExpectedStatus,
    BenchmarkObservedStatus,
    BenchmarkResult,
    BenchmarkRun,
    BenchmarkSuite,
    etp_matrix_benchmark_suite_metadata,
    logikey_methodology_benchmark_suite_metadata,
)
from mathgraph.correspondence import (
    CorrespondenceClaim,
    CorrespondenceDirection,
    CorrespondenceStatus,
)
from mathgraph.interpretation_choice import ChoicePointStatus, InterpretationChoicePoint
from mathgraph.workbench_presets import (
    build_logikey_style_workbench_bundle,
    build_mathgraph_etp_workbench_bundle,
)
from mathgraph.proof_motifs import (
    ProofMotif,
    ProofMotifKind,
    ProofRouteStatus,
    infer_proof_motif_kind,
    make_proof_motif_id,
)
from mathgraph.lemma_candidates import (
    CutIntroductionKind,
    LemmaCandidate,
    LemmaCandidateStatus,
    canonical_lemma_name,
    make_lemma_candidate_id,
)
from mathgraph.lean_artifacts import (
    LeanArtifact,
    LeanArtifactKind,
    LeanVerificationStatus,
    render_lean_skeleton,
)
from mathgraph.proof_atlas import ProofAtlas, build_proof_atlas_from_true_rows
from mathgraph.proof_importers import (
    discover_true_proof_artifacts,
    import_true_proof_artifacts_to_store,
    load_true_proof_rows,
    normalize_true_proof_row,
)
from mathgraph.metabolic_cycle import (
    MetabolicCycleConfig,
    MetabolicCycleResult,
    MetabolicCycleStageResult,
    run_metabolic_cycle,
)
from mathgraph.m0_certificate_factory import (
    M0EpisodeConfig,
    M0EpisodeMetrics,
    M0EpisodeResult,
    M0PairResult,
    run_m0_episode,
)
from mathgraph.m0_audit import AuditFinding, AuditReport, audit_m0_store
from mathgraph.terminal_contract import (
    TerminalContractResult,
    VerifierBoundary,
)
from mathgraph.metabolic_diagnostics import (
    MetabolicDiagnostics,
    compute_derived_amplification_factor,
    compute_residual_compression_gain,
    evaluate_better_shaped_unknown,
)
from mathgraph.synthetic_cycle_data import build_synthetic_metabolic_frontier
from mathgraph.types import (
    ExtensionalCollapsePolicy,
    HyperintensionalIdentityMode,
    MathGraphType,
    ObjectIdentityMode,
    TypeParseError,
    TypedObject,
    UniquenessStatus,
    canonical_encoded_object_id,
    normalize_type_expr,
    parse_type_expr,
    should_merge_objects,
)
from mathgraph.artifact_importers import (
    load_v1662_elevated_false_certificates,
    load_v167_obstructions,
    load_v167_reason_nodes,
    load_v167_root_nodes,
)
from mathgraph.hashing import (
    canonical_json,
    content_id,
    hash_certificate,
    hash_file,
    hash_trace,
    sha256_hex,
    sha256_json,
    sha256_text,
)
from mathgraph.flywheel import (
    FlywheelConfig,
    FlywheelResult,
    FlywheelStageResult,
    run_mathgraph_flywheel,
)
from mathgraph.frontier_builder import (
    FrontierBuilderConfig,
    FrontierBuilderResult,
    FrontierCandidate,
    KnownPairFilter,
    build_candidate_frontier,
)
from mathgraph.finite_countermodel_executor import (
    FiniteCountermodelConfig,
    FiniteCountermodelResult,
    FiniteCountermodelRunResult,
    run_finite_countermodel_tasks,
)
from mathgraph.htilt_scheduler import (
    HTiltScheduler,
    HTiltSchedulerStats,
    HTiltScoreBreakdown,
    ScheduledTask,
    SchedulerInputPair,
)
from mathgraph.kernel import Kernel
from mathgraph.kernel_oracle import KernelOracle, OracleAnswer
from mathgraph.lawbook import CertificateLawbook
from mathgraph.lawbook_store import LawbookStore, LawbookStoreStats
from mathgraph.ledger import JsonlLedger
from mathgraph.outcome_dataset import (
    CompoundingDiagnostics,
    OutcomeDatasetBuilder,
    OutcomeDatasetStats,
    PairOutcome,
    extract_pair_features as extract_outcome_pair_features,
)
from mathgraph.obstruction_atlas import ConstructorPressure, ObstructionNode
from mathgraph.pair_advisor import PairAdvice, advise_many, advise_pair, extract_pair_features
from mathgraph.reason_nodes import ReasonNode
from mathgraph.refutations import RefutationCertificate
from mathgraph.root_consolidation import consolidate_root_nodes
from mathgraph.root_nodes import (
    RootAlias,
    RootCertificateCoverage,
    RootNode,
    RootObstructionLink,
    RootReasonLink,
)
from mathgraph.root_discovery import (
    CompletionTelemetryRow,
    ConstructorFamilyCard,
    ObstructionCandidate,
    RootCandidate,
    build_constructor_family_cards,
    build_replay_queue,
    distill_obstruction_candidates,
    distill_root_candidates,
    summarize_root_discovery,
)
from mathgraph.root_oracle import RootNodeOracle
from mathgraph.route_instructor import (
    RouteInstruction,
    build_all_route_instructions,
    build_route_instruction,
    route_instruction_report,
)
from mathgraph.route_learner import (
    RouteBasinKey,
    RouteLearner,
    RouteLearnerStats,
    RoutePolicyCard,
    RouteRecommendation,
    make_basin_key,
)
from mathgraph.task_planner import (
    CertificateTask,
    plan_certificate_task,
    plan_many_certificate_tasks,
)
from mathgraph.task_queue import (
    TaskQueueConfig,
    TaskQueueItem,
    TaskQueueResult,
    build_task_queue,
)
from mathgraph.task_runner import (
    TaskOutcome,
    TaskRunSummary,
    execute_certificate_task,
    execute_many_certificate_tasks,
    read_outcomes_json,
    read_outcomes_jsonl,
    residual_outcomes,
    summarize_task_outcomes,
    write_outcomes_json,
    write_outcomes_jsonl,
)
from mathgraph.terms import Term, parse_term
from mathgraph.trace import Trace
from mathgraph.trust import ProvenanceType, TrustLevel
from mathgraph.verify_api import MathGraphVerifier, VerifyConfig, VerifyRequest, VerifyResult

__all__ = [
    "Certificate",
    "CertificateAssimilationConfig",
    "CertificateAssimilationResult",
    "CertificateAssimilationSummary",
    "CertificateCorpus",
    "CertificateLawbook",
    "CertificateTask",
    "ConstructorPressure",
    "AssetDiscoveryConfig",
    "AssetDiscoveryResult",
    "AssetMaterializationConfig",
    "AssetMaterializationResult",
    "AssimilationLearningRecord",
    "ChewingSmokeConfig",
    "ChewingSmokeResult",
    "ChewingSmokeStageResult",
    "CompoundingDiagnostics",
    "CountermodelImportConfig",
    "CountermodelImportResult",
    "CountermodelImportRunResult",
    "DerivedCertificate",
    "DerivedCertificateGenerator",
    "DerivedCertificateStats",
    "DomainKernel",
    "Equation",
    "GeneralClaim",
    "EpisodeLearningConfig",
    "EpisodeLearningResult",
    "FiniteCountermodelConfig",
    "FiniteCountermodelResult",
    "FiniteCountermodelRunResult",
    "FlywheelConfig",
    "FlywheelResult",
    "FlywheelStageResult",
    "FrontierBuilderConfig",
    "FrontierBuilderResult",
    "FrontierCandidate",
    "HTiltScheduler",
    "HTiltSchedulerStats",
    "HTiltScoreBreakdown",
    "HostVerifier",
    "ImportedTheoryObject",
    "ImportedTheoryRelation",
    "Kernel",
    "KernelOracle",
    "KnownPairFilter",
    "JsonlLedger",
    "LawbookStore",
    "LawbookStoreStats",
    "MathGraphVerifier",
    "OracleAnswer",
    "ObstructionNode",
    "OutcomeDatasetBuilder",
    "OutcomeDatasetStats",
    "PairAdvice",
    "PairOutcome",
    "ProvenanceType",
    "ReasonNode",
    "RefutationCertificate",
    "RouteBasinKey",
    "RouteLearner",
    "RouteLearnerStats",
    "RouteYieldStats",
    "ConstructorYieldStats",
    "ResidualBasinStats",
    "RootAlias",
    "RootCertificateCoverage",
    "TaskOutcome",
    "TaskQueueConfig",
    "TaskQueueItem",
    "TaskQueueResult",
    "TaskRunSummary",
    "canonical_json",
    "RouteInstruction",
    "RootNode",
    "RootNodeOracle",
    "CompletionTelemetryRow",
    "ConstructorFamilyCard",
    "ObstructionCandidate",
    "RootCandidate",
    "build_constructor_family_cards",
    "build_replay_queue",
    "distill_obstruction_candidates",
    "distill_root_candidates",
    "summarize_root_discovery",
    "RootObstructionLink",
    "RootReasonLink",
    "RoutePolicyCard",
    "RouteRecommendation",
    "ScheduledTask",
    "SchedulerInputPair",
    "SemanticEmbedding",
    "SemanticEmbeddingKind",
    "build_all_route_instructions",
    "build_route_instruction",
    "build_candidate_frontier",
    "build_task_queue",
    "advise_many",
    "advise_pair",
    "content_id",
    "consolidate_root_nodes",
    "discover_mathgraph_assets",
    "extract_pair_features",
    "extract_outcome_pair_features",
    "execute_certificate_task",
    "execute_many_certificate_tasks",
    "hash_certificate",
    "hash_file",
    "hash_trace",
    "import_finite_countermodel_results",
    "import_closure_oracle_csv",
    "import_table_registry_csv",
    "import_v16_6_2_elevated_false_dir",
    "import_v16_7_root_atlas_dir",
    "learn_from_assimilation_episodes",
    "load_v1662_elevated_false_certificates",
    "load_v167_obstructions",
    "load_v167_reason_nodes",
    "load_v167_root_nodes",
    "make_basin_key",
    "make_aot_domain_kernel",
    "materialize_mathgraph_assets",
    "sha256_hex",
    "sha256_json",
    "sha256_text",
    "Term",
    "TerminalForm",
    "parse_equation",
    "parse_term",
    "plan_certificate_task",
    "plan_many_certificate_tasks",
    "read_outcomes_json",
    "read_outcomes_jsonl",
    "residual_outcomes",
    "register_aot_kernel",
    "register_domain_kernel_in_store",
    "register_etp_kernel",
    "route_instruction_report",
    "run_mathgraph_flywheel",
    "run_chewing_smoke",
    "run_certificate_assimilation",
    "run_finite_countermodel_tasks",
    "summarize_task_outcomes",
    "Trace",
    "TrustLevel",
    "TheoryObjectKind",
    "TheoryRelationKind",
    "VerificationStatus",
    "VerifyConfig",
    "VerifyRequest",
    "VerifyResult",
    "write_outcomes_json",
    "write_outcomes_jsonl",
    "ArtifactRisk",
    "AnalyticTruth",
    "ContainmentMode",
    "DenotationRecord",
    "DenotationStatus",
    "DomainKernelSemanticEmbedding",
    "EmbeddingKind",
    "ExtensionalCollapsePolicy",
    "FormalWorld",
    "FormalWorldKind",
    "GuardSeverity",
    "HyperintensionalIdentityMode",
    "ImportedTheoryObjectKind",
    "LanguageFragment",
    "MathGraphType",
    "ObjectIdentityMode",
    "ParadoxGuard",
    "ParadoxGuardKind",
    "ParadoxGuardResult",
    "PredicateKind",
    "PredicationFact",
    "PredicationMode",
    "ProofTransportStatus",
    "ReasonContainmentRecord",
    "TheoryDenotation",
    "TheoryObjectificationMap",
    "TheoryReading",
    "TypeParseError",
    "TypedObject",
    "UniquenessStatus",
    "aot_complex_term_guard",
    "aot_formal_world_precedent",
    "aot_l23_precedent_fragment",
    "canonical_encoded_object_id",
    "can_promote_denotation",
    "encodes",
    "etp_magma_equations_fragment",
    "etp_magma_formal_world",
    "exemplifies",
    "make_etp_domain_kernel",
    "normalize_type_expr",
    "parse_type_expr",
    "require_denotes",
    "semantic_embedding_artifact_guard",
    "set_collapse_guard",
    "should_merge_objects",
    "AOTScanResult",
    "AOTScannedDeclaration",
    "FormulaRole",
    "HostObjectTheoremLink",
    "InferenceRule",
    "IsabelleExportRecord",
    "IsabelleExportStatus",
    "ObjectLanguageFormula",
    "ObjectLanguageKind",
    "ObjectLanguageTerm",
    "ProofMethod",
    "ProofMethodKind",
    "TheoryDeclaration",
    "TheoryDeclarationKind",
    "normalize_object_language_text",
    "scan_aot_repository",
    "AutomationBias",
    "BackendRole",
    "BenchmarkCase",
    "BenchmarkExpectedStatus",
    "BenchmarkObservedStatus",
    "BenchmarkResult",
    "BenchmarkRun",
    "BenchmarkSuite",
    "ChoicePointStatus",
    "CombinationMethod",
    "CompletenessStatus",
    "ConflictPolicy",
    "CorrespondenceClaim",
    "CorrespondenceDirection",
    "CorrespondenceStatus",
    "EmbeddingStrategy",
    "EmbeddingStrategyProfile",
    "FaithfulnessAssessment",
    "FaithfulnessStatus",
    "InterpretationChoicePoint",
    "LogicCombination",
    "LogicWorkbench",
    "ModelFinderResult",
    "ModelFinderStatus",
    "ProofFinderResult",
    "ProofFinderStatus",
    "SemanticsRepresentation",
    "SoundnessStatus",
    "SyntaxRepresentation",
    "VerifierBackendKind",
    "VerifierBackendProfile",
    "WorkbenchLayer",
    "WorkbenchLifecycleStatus",
    "build_logikey_style_workbench_bundle",
    "build_mathgraph_etp_workbench_bundle",
    "etp_matrix_benchmark_suite_metadata",
    "isabelle_nitpick_backend_placeholder",
    "isabelle_nunchaku_backend_placeholder",
    "isabelle_sledgehammer_backend_placeholder",
    "lean_backend_placeholder",
    "logikey_methodology_benchmark_suite_metadata",
    "logikey_style_workbench",
    "mathgraph_default_workbench",
    "python_finite_table_checker_backend",
    "ProofMotif",
    "ProofMotifKind",
    "ProofRouteStatus",
    "make_proof_motif_id",
    "infer_proof_motif_kind",
    "LemmaCandidate",
    "LemmaCandidateStatus",
    "CutIntroductionKind",
    "make_lemma_candidate_id",
    "canonical_lemma_name",
    "LeanArtifact",
    "LeanArtifactKind",
    "LeanVerificationStatus",
    "render_lean_skeleton",
    "ProofAtlas",
    "build_proof_atlas_from_true_rows",
    "discover_true_proof_artifacts",
    "load_true_proof_rows",
    "normalize_true_proof_row",
    "import_true_proof_artifacts_to_store",
    "MetabolicCycleConfig",
    "MetabolicCycleResult",
    "MetabolicCycleStageResult",
    "MetabolicDiagnostics",
    "M0EpisodeConfig",
    "M0EpisodeMetrics",
    "M0EpisodeResult",
    "M0PairResult",
    "MathGraphAnswer",
    "MathGraphAuditError",
    "MathGraphClient",
    "MathGraphClientConfig",
    "MathGraphHTTPServer",
    "MathGraphRequestHandler",
    "AuditFinding",
    "AuditReport",
    "TerminalContractResult",
    "VerifierBoundary",
    "build_synthetic_metabolic_frontier",
    "compute_derived_amplification_factor",
    "compute_residual_compression_gain",
    "evaluate_better_shaped_unknown",
    "run_m0_episode",
    "audit_m0_store",
    "make_server",
    "run_metabolic_cycle",
]
