"""Lean theorem/proof artifact metadata and conservative skeleton rendering."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from mathgraph.hashing import content_id
from mathgraph.lemma_candidates import LemmaCandidate
from mathgraph.trust import TrustLevel, trust_level


class LeanArtifactKind(str, Enum):
    THEOREM_STATEMENT = "THEOREM_STATEMENT"
    PROOF_SKETCH = "PROOF_SKETCH"
    COMPLETE_PROOF = "COMPLETE_PROOF"
    IMPORT_DECLARATION = "IMPORT_DECLARATION"
    INSTANCE_PROOF = "INSTANCE_PROOF"
    FAMILY_PROOF = "FAMILY_PROOF"
    UNKNOWN = "UNKNOWN"


class LeanVerificationStatus(str, Enum):
    NOT_ATTEMPTED = "NOT_ATTEMPTED"
    GENERATED = "GENERATED"
    LEAN_VERIFIED = "LEAN_VERIFIED"
    LEAN_FAILED = "LEAN_FAILED"
    IMPORTED_VERIFIED = "IMPORTED_VERIFIED"
    IMPORTED_UNCHECKED = "IMPORTED_UNCHECKED"
    UNKNOWN = "UNKNOWN"


SAFE_TRUST = {TrustLevel.LEAN_VERIFIED, TrustLevel.DERIVED_CHAIN_VERIFIED}


def make_lean_artifact_id(name: str, artifact_kind: str, statement: str | None = None) -> str:
    return content_id("lean_artifact", {"name": name, "artifact_kind": artifact_kind, "statement": statement or ""})


@dataclass(frozen=True)
class LeanArtifact:
    lean_artifact_id: str
    artifact_kind: LeanArtifactKind | str
    name: str
    domain_kernel_id: str | None = None
    formal_world_id: str | None = None
    theorem_name: str | None = None
    statement: str | None = None
    proof_text: str | None = None
    imports: list[str] = field(default_factory=list)
    depends_on: list[str] = field(default_factory=list)
    verification_status: LeanVerificationStatus | str = LeanVerificationStatus.NOT_ATTEMPTED
    trust_level: str = "ADVISORY_ROUTE"
    provenance_type: str = "GENERATED"
    source_file: str | None = None
    line_start: int | None = None
    line_end: int | None = None
    payload: dict[str, Any] = field(default_factory=dict)

    def is_verified(self) -> bool:
        return _value(self.verification_status) in {
            LeanVerificationStatus.LEAN_VERIFIED.value,
            LeanVerificationStatus.IMPORTED_VERIFIED.value,
        }

    def is_authoritative(self) -> bool:
        return self.is_verified() and trust_level(self.trust_level) in SAFE_TRUST

    def summary(self) -> dict[str, Any]:
        return {
            "lean_artifact_id": self.lean_artifact_id,
            "name": self.name,
            "artifact_kind": _value(self.artifact_kind),
            "verification_status": _value(self.verification_status),
            "authoritative": self.is_authoritative(),
            "truth_boundary": "Lean sketches are not Lean verification.",
        }

    def to_dict(self) -> dict[str, Any]:
        return {
            "lean_artifact_id": self.lean_artifact_id,
            "artifact_kind": _value(self.artifact_kind),
            "name": self.name,
            "domain_kernel_id": self.domain_kernel_id,
            "formal_world_id": self.formal_world_id,
            "theorem_name": self.theorem_name,
            "statement": self.statement,
            "proof_text": self.proof_text,
            "imports": list(self.imports),
            "depends_on": list(self.depends_on),
            "verification_status": _value(self.verification_status),
            "trust_level": self.trust_level,
            "provenance_type": self.provenance_type,
            "source_file": self.source_file,
            "line_start": self.line_start,
            "line_end": self.line_end,
            "payload": dict(self.payload),
        }


def render_lean_skeleton(lemma_candidate: LemmaCandidate) -> str:
    theorem_name = lemma_candidate.candidate_name
    statement = lemma_candidate.lean_statement or "True"
    return (
        "import Mathlib\n\n"
        "/-!\n"
        "Generated by MathGraph.\n\n"
        f"Lemma candidate: {theorem_name}\n"
        f"Status: {lemma_candidate.status.value if hasattr(lemma_candidate.status, 'value') else lemma_candidate.status}\n"
        f"Trust: {lemma_candidate.trust_level}\n\n"
        "This file is not authoritative until checked by Lean.\n"
        "-/\n\n"
        f"theorem {theorem_name} :\n"
        f"  {statement} := by\n"
        "  trivial\n"
    )


def _value(value: Any) -> str:
    return value.value if hasattr(value, "value") else str(value)
