"""Named obstructions recognized by the initial kernel."""

NO_COUNTERMODEL_IN_GIVEN_FINITE_MAGMA = "NO_COUNTERMODEL_IN_GIVEN_FINITE_MAGMA"
ADAPTER_NOT_AVAILABLE = "ADAPTER_NOT_AVAILABLE"
UNSUPPORTED_ROUTE = "UNSUPPORTED_ROUTE"
