"""
Auto-generated by MathGraph v17.5b.

This module packages SAIR v17 MathGraph lawbook memory into reusable code.

Authority boundary:
- Constructor schemas are empirical routing/constructor memory.
- Individual claims still require Lean verification.
- Named obstruction patterns guide routing; they do not prove or refute implication by themselves.
- Only Lean-verified proof traces or finite countermodel certificates are terminal.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict


TERMINAL_TRUE_STATUSES = {
    "lean_verified",
    "LEAN_VERIFIED",
    "VERIFIED_PROOF",
    "verified",
}

TERMINAL_FALSE_STATUSES = {
    "finite_countermodel_found",
    "FINITE_COUNTERMODEL",
    "countermodel_verified",
}

ADVISORY_STATUSES = {
    "candidate_certificate",
    "lean_artifact_generated",
    "failed_search",
    "finite_failed_small_n",
    "finite_failed_structured",
    "possibly_true",
    "needs_proof_side",
    "needs_larger_model",
    "residual",
    "named_obstruction_pattern",
}


@dataclass(frozen=True)
class TerminalBoundaryDecision:
    terminal_safe: bool
    terminal_form: str
    reason: str
    may_update_truth_mask: bool


def decide_terminal_boundary(record: Dict[str, Any]) -> TerminalBoundaryDecision:
    terminal_form = str(record.get("terminal_form", record.get("certificate_kind", "")))
    status = str(record.get("certificate_status", record.get("status", "")))
    official_true = record.get("official_true", None)

    if terminal_form == "VERIFIED_PROOF" and status in TERMINAL_TRUE_STATUSES:
        if official_true is False:
            return TerminalBoundaryDecision(
                terminal_safe=False,
                terminal_form=terminal_form,
                reason="Rejected: verified proof row is marked official_false.",
                may_update_truth_mask=False,
            )
        return TerminalBoundaryDecision(
            terminal_safe=True,
            terminal_form="VERIFIED_PROOF",
            reason="Accepted terminal TRUE only because Lean verification status is present.",
            may_update_truth_mask=True,
        )

    if terminal_form == "FINITE_COUNTERMODEL" and status in TERMINAL_FALSE_STATUSES:
        return TerminalBoundaryDecision(
            terminal_safe=True,
            terminal_form="FINITE_COUNTERMODEL",
            reason="Accepted terminal FALSE only because finite countermodel certificate status is present.",
            may_update_truth_mask=True,
        )

    if terminal_form == "NAMED_OBSTRUCTION":
        return TerminalBoundaryDecision(
            terminal_safe=False,
            terminal_form="NAMED_OBSTRUCTION",
            reason="Named obstruction is routing memory unless explicitly attached to a terminal certificate policy.",
            may_update_truth_mask=False,
        )

    return TerminalBoundaryDecision(
        terminal_safe=False,
        terminal_form=terminal_form or "UNKNOWN",
        reason="Not terminal: constructor output, failed search, or advisory trace.",
        may_update_truth_mask=False,
    )


def assert_terminal_true_record(record: Dict[str, Any]) -> None:
    decision = decide_terminal_boundary(record)
    if not (decision.terminal_safe and decision.terminal_form == "VERIFIED_PROOF"):
        raise AssertionError(decision.reason)


def is_terminal_true_record(record: Dict[str, Any]) -> bool:
    decision = decide_terminal_boundary(record)
    return decision.terminal_safe and decision.terminal_form == "VERIFIED_PROOF"
