"""
Auto-generated by MathGraph v17.5b.

This module packages SAIR v17 MathGraph lawbook memory into reusable code.

Authority boundary:
- Constructor schemas are empirical routing/constructor memory.
- Individual claims still require Lean verification.
- Named obstruction patterns guide routing; they do not prove or refute implication by themselves.
- Only Lean-verified proof traces or finite countermodel certificates are terminal.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List

try:
    from .sair_v17_constructors import choose_constructor_for_error, constructor_policy
except Exception:
    from sair_v17_constructors import choose_constructor_for_error, constructor_policy


NEXT_ROUTES: List[Dict[str, Any]] = [{'router_rank': 1, 'next_route': 'package_fixed_header_into_all_lean_emitters', 'route_type': 'repo_integration', 'constructor_family': 'FIXED_HEADER_EXACT_REPLAY', 'recommended_engine': 'make_universe_u_header_mandatory', 'expected_terminal_form': 'VERIFIED_PROOF_OR_NAMED_OBSTRUCTION', 'policy': 'Every future Lean emitter using `{M : Type u}` must emit `universe u` first. This fixed a false failure class.', 'router_score': 10.0}, {'router_rank': 2, 'next_route': 'package_fast_witness_completed_one_bridge_replay', 'route_type': 'constructor_integration', 'constructor_family': 'FAST_WITNESS_COMPLETED_ONE_BRIDGE', 'recommended_engine': 'no_bfs_witness_completed_one_bridge_first', 'expected_terminal_form': 'VERIFIED_PROOF_OR_NAMED_OBSTRUCTION', 'policy': 'Use fast one-bridge replay before bounded closure/BFS. v17.4J showed closure can explode; v17.4J2 found certificates quickly.', 'router_score': 9.0}, {'router_rank': 3, 'next_route': 'package_explicit_subposition_congrarg_bridge_repair', 'route_type': 'constructor_integration', 'constructor_family': 'EXPLICIT_SUBPOSITION_CONGRARG_BRIDGE_REPAIR', 'recommended_engine': 'explicit_congrarg_two_step_symm_s2_for_rw_failures', 'expected_terminal_form': 'VERIFIED_PROOF_OR_NAMED_OBSTRUCTION', 'policy': 'When bridge rw leaves UNSOLVED_GOALS or type mismatch, try explicit subposition congrArg/calc repair before broadening.', 'router_score': 8.0}, {'router_rank': 4, 'next_route': 'build_sair_v17_constructor_replay_module_in_repo', 'route_type': 'repo_integration', 'constructor_family': 'MATHGRAPH_MEMORY_LAYER', 'recommended_engine': 'importer_to_lawbook_to_schema_registry_to_replay', 'expected_terminal_form': 'VERIFIED_PROOF_OR_NAMED_OBSTRUCTION', 'policy': 'Do not broaden the global residual until v17 constructors are packaged as reusable MathGraph modules with terminal-boundary checks.', 'router_score': 7.0}]


@dataclass(frozen=True)
class ReplayDecision:
    route_name: str
    constructor_family: str
    recommended_engine: str
    expected_terminal_form: str
    policy: str
    router_score: float


def next_routes() -> List[ReplayDecision]:
    out: List[ReplayDecision] = []
    for r in NEXT_ROUTES:
        out.append(ReplayDecision(
            route_name=str(r.get("next_route", "")),
            constructor_family=str(r.get("constructor_family", "")),
            recommended_engine=str(r.get("recommended_engine", "")),
            expected_terminal_form=str(r.get("expected_terminal_form", "VERIFIED_PROOF_OR_NAMED_OBSTRUCTION")),
            policy=str(r.get("policy", "")),
            router_score=float(r.get("router_score", 0.0) or 0.0),
        ))
    return sorted(out, key=lambda x: -x.router_score)


def route_failed_attempt(error_class: str, source_skeleton: str = "", target_skeleton: str = "") -> Dict[str, Any]:
    constructors = choose_constructor_for_error(error_class, source_skeleton, target_skeleton)
    return {
        "error_class": error_class,
        "source_skeleton": source_skeleton,
        "target_skeleton": target_skeleton,
        "recommended_constructors": [c.__dict__ for c in constructors[:10]],
        "policy": constructor_policy(),
        "authority_warning": (
            "This is a constructor route only. It does not verify truth. "
            "Every emitted claim must be Lean checked before entering terminal memory."
        ),
    }


def route_global_next_step() -> Dict[str, Any]:
    routes = next_routes()
    return {
        "top_route": routes[0].__dict__ if routes else {},
        "all_routes": [r.__dict__ for r in routes],
        "authority_warning": (
            "Do not broaden the global residual until v17 constructors are packaged "
            "as reusable modules with terminal-boundary checks."
        ),
    }
