#!/usr/bin/env python
"""Offline asset distiller for verified FALSE finite-magma certificates."""

from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROJECT_ROOT = ROOT.parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from competitions.sair_stage2.src.equation_core import canonical_equation, parse_equation  # noqa: E402
from competitions.sair_stage2.src.false_constructors import prove_false  # noqa: E402
from competitions.sair_stage2.src.lean_false_emitter import build_false_certificate  # noqa: E402


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--equations-path")
    parser.add_argument("--matrix-path")
    parser.add_argument("--true-proofs-csv", action="append", default=[])
    parser.add_argument("--false-certs-jsonl", action="append", default=[])
    parser.add_argument("--max-pairs", type=int)
    parser.add_argument("--sample-size", type=int)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--out-dir", required=True)
    args = parser.parse_args(argv)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    if not args.equations_path or not args.matrix_path or not Path(args.equations_path).exists() or not Path(args.matrix_path).exists():
        report = {"status": "skipped", "reason": "ETP equations or matrix file not found", "generated_assets": False}
        _write(out_dir, report, [], "EXACT_TRUE = {}\nEXACT_FALSE = {}\nTABLE_BANK = []\nRULE_FAMILIES = []\n")
        print(json.dumps(report, sort_keys=True))
        return 0
    try:
        import numpy as np
    except Exception as exc:
        report = {"status": "skipped", "reason": "numpy unavailable: %s" % exc, "generated_assets": False}
        _write(out_dir, report, [], "EXACT_TRUE = {}\nEXACT_FALSE = {}\nTABLE_BANK = []\nRULE_FAMILIES = []\n")
        print(json.dumps(report, sort_keys=True))
        return 0

    equations = [line.strip() for line in Path(args.equations_path).read_text(encoding="utf-8").splitlines() if line.strip()]
    matrix = np.load(args.matrix_path)
    false_pairs = [(i, j) for i in range(len(equations)) for j in range(len(equations)) if not bool(matrix[i, j])]
    random.Random(args.seed).shuffle(false_pairs)
    limit = args.sample_size if args.sample_size is not None else args.max_pairs
    if limit is not None:
        false_pairs = false_pairs[:limit]

    records = []
    exact_false = {}
    family_counts = {}
    for i, j in false_pairs:
        try:
            eq1 = parse_equation(equations[i])
            eq2 = parse_equation(equations[j])
            result = prove_false(eq1, eq2)
        except Exception:
            result = None
        if not result:
            continue
        cert = build_false_certificate(i, j, equations[i], equations[j], result["certificate"]["table"])
        if cert is None:
            continue
        data = cert.to_dict()
        data["status"] = "python_verified"
        records.append(data)
        family_counts[data["family"]] = family_counts.get(data["family"], 0) + 1
        compact_cert = {
            "carrier_size": data["n"],
            "table": data["table"],
            "violating_assignment": data["witness"],
            "source_satisfied": True,
            "target_violated": True,
        }
        exact_false[str(i) + "->" + str(j)] = compact_cert
        try:
            exact_false[canonical_equation(parse_equation(equations[i])) + "=>" + canonical_equation(parse_equation(equations[j]))] = compact_cert
        except Exception:
            pass

    assets_text = _assets_text(exact_false)
    report = {
        "status": "completed",
        "false_pairs_considered": len(false_pairs),
        "verified_false_certificates": len(records),
        "family_counts": family_counts,
        "generated_assets": True,
        "asset_exact_false_entries": len(exact_false),
        "asset_bytes": len(assets_text.encode("utf-8")),
    }
    _write(out_dir, report, records, assets_text)
    print(json.dumps(report, sort_keys=True))
    return 0


def _assets_text(exact_false):
    return (
        "# Generated by competitions/sair_stage2/scripts/distill_assets.py\n"
        "EXACT_TRUE = {}\n"
        "EXACT_FALSE = "
        + repr(exact_false)
        + "\nTABLE_BANK = []\nRULE_FAMILIES = []\n"
    )


def _write(out_dir, report, records, assets_text):
    (out_dir / "distilled_assets_report.json").write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")
    (out_dir / "false_asset_coverage_summary.json").write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")
    with (out_dir / "false_certificate_candidates.jsonl").open("w", encoding="utf-8") as handle:
        for record in records:
            handle.write(json.dumps(record, sort_keys=True) + "\n")
    (out_dir / "distilled_assets_report.md").write_text("# Distilled Assets Report\n\n```json\n%s\n```\n" % json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")
    (out_dir / "generated_solver_assets.py").write_text(assets_text, encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())

